package app.fmgp.money

//import sala.language.strictEquality
sealed trait Currency //derives Eql

/** Currency represents one currency of the ISO_4217 currencies list
  * @see [[https://en.wikipedia.org/wiki/ISO_4217]]
  */
object AED extends Currency { given Eql[AED.type, AED.type] = Eql.derived } //AED have the numeric code 784
object AFN extends Currency { given Eql[AFN.type, AFN.type] = Eql.derived } //AFN have the numeric code 971
object ALL extends Currency { given Eql[ALL.type, ALL.type] = Eql.derived } //ALL have the numeric code 008
object AMD extends Currency { given Eql[AMD.type, AMD.type] = Eql.derived } //AMD have the numeric code 051
object ANG extends Currency { given Eql[ANG.type, ANG.type] = Eql.derived } //ANG have the numeric code 532
object AOA extends Currency { given Eql[AOA.type, AOA.type] = Eql.derived } //AOA have the numeric code 973
object ARS extends Currency { given Eql[ARS.type, ARS.type] = Eql.derived } //ARS have the numeric code 032
object AUD extends Currency { given Eql[AUD.type, AUD.type] = Eql.derived } //AUD have the numeric code 036
object AWG extends Currency { given Eql[AWG.type, AWG.type] = Eql.derived } //AWG have the numeric code 533
object AZN extends Currency { given Eql[AZN.type, AZN.type] = Eql.derived } //AZN have the numeric code 944
object BAM extends Currency { given Eql[BAM.type, BAM.type] = Eql.derived } //BAM have the numeric code 977
object BBD extends Currency { given Eql[BBD.type, BBD.type] = Eql.derived } //BBD have the numeric code 052
object BDT extends Currency { given Eql[BDT.type, BDT.type] = Eql.derived } //BDT have the numeric code 050
object BGN extends Currency { given Eql[BGN.type, BGN.type] = Eql.derived } //BGN have the numeric code 975
object BHD extends Currency { given Eql[BHD.type, BHD.type] = Eql.derived } //BHD have the numeric code 048
object BIF extends Currency { given Eql[BIF.type, BIF.type] = Eql.derived } //BIF have the numeric code 108
object BMD extends Currency { given Eql[BMD.type, BMD.type] = Eql.derived } //BMD have the numeric code 060
object BND extends Currency { given Eql[BND.type, BND.type] = Eql.derived } //BND have the numeric code 096
object BOB extends Currency { given Eql[BOB.type, BOB.type] = Eql.derived } //BOB have the numeric code 068
object BOV extends Currency { given Eql[BOV.type, BOV.type] = Eql.derived } //BOV have the numeric code 984
object BRL extends Currency { given Eql[BRL.type, BRL.type] = Eql.derived } //BRL have the numeric code 986
object BSD extends Currency { given Eql[BSD.type, BSD.type] = Eql.derived } //BSD have the numeric code 044
object BTN extends Currency { given Eql[BTN.type, BTN.type] = Eql.derived } //BTN have the numeric code 064
object BWP extends Currency { given Eql[BWP.type, BWP.type] = Eql.derived } //BWP have the numeric code 072
object BYN extends Currency { given Eql[BYN.type, BYN.type] = Eql.derived } //BYN have the numeric code 933
object BZD extends Currency { given Eql[BZD.type, BZD.type] = Eql.derived } //BZD have the numeric code 084
object CAD extends Currency { given Eql[CAD.type, CAD.type] = Eql.derived } //CAD have the numeric code 124
object CDF extends Currency { given Eql[CDF.type, CDF.type] = Eql.derived } //CDF have the numeric code 976
object CHE extends Currency { given Eql[CHE.type, CHE.type] = Eql.derived } //CHE have the numeric code 947
object CHF extends Currency { given Eql[CHF.type, CHF.type] = Eql.derived } //CHF have the numeric code 756
object CHW extends Currency { given Eql[CHW.type, CHW.type] = Eql.derived } //CHW have the numeric code 948
object CLF extends Currency { given Eql[CLF.type, CLF.type] = Eql.derived } //CLF have the numeric code 990
object CLP extends Currency { given Eql[CLP.type, CLP.type] = Eql.derived } //CLP have the numeric code 152
object CNY extends Currency { given Eql[CNY.type, CNY.type] = Eql.derived } //CNY have the numeric code 156
object COP extends Currency { given Eql[COP.type, COP.type] = Eql.derived } //COP have the numeric code 170
object COU extends Currency { given Eql[COU.type, COU.type] = Eql.derived } //COU have the numeric code 970
object CRC extends Currency { given Eql[CRC.type, CRC.type] = Eql.derived } //CRC have the numeric code 188
object CUC extends Currency { given Eql[CUC.type, CUC.type] = Eql.derived } //CUC have the numeric code 931
object CUP extends Currency { given Eql[CUP.type, CUP.type] = Eql.derived } //CUP have the numeric code 192
object CVE extends Currency { given Eql[CVE.type, CVE.type] = Eql.derived } //CVE have the numeric code 132
object CZK extends Currency { given Eql[CZK.type, CZK.type] = Eql.derived } //CZK have the numeric code 203
object DJF extends Currency { given Eql[DJF.type, DJF.type] = Eql.derived } //DJF have the numeric code 262
object DKK extends Currency { given Eql[DKK.type, DKK.type] = Eql.derived } //DKK have the numeric code 208
object DOP extends Currency { given Eql[DOP.type, DOP.type] = Eql.derived } //DOP have the numeric code 214
object DZD extends Currency { given Eql[DZD.type, DZD.type] = Eql.derived } //DZD have the numeric code 012
object EGP extends Currency { given Eql[EGP.type, EGP.type] = Eql.derived } //EGP have the numeric code 818
object ERN extends Currency { given Eql[ERN.type, ERN.type] = Eql.derived } //ERN have the numeric code 232
object ETB extends Currency { given Eql[ETB.type, ETB.type] = Eql.derived } //ETB have the numeric code 230
object EUR extends Currency { given Eql[EUR.type, EUR.type] = Eql.derived } //EUR have the numeric code 978
object FJD extends Currency { given Eql[FJD.type, FJD.type] = Eql.derived } //FJD have the numeric code 242
object FKP extends Currency { given Eql[FKP.type, FKP.type] = Eql.derived } //FKP have the numeric code 238
object GBP extends Currency { given Eql[GBP.type, GBP.type] = Eql.derived } //GBP have the numeric code 826
object GEL extends Currency { given Eql[GEL.type, GEL.type] = Eql.derived } //GEL have the numeric code 981
object GHS extends Currency { given Eql[GHS.type, GHS.type] = Eql.derived } //GHS have the numeric code 936
object GIP extends Currency { given Eql[GIP.type, GIP.type] = Eql.derived } //GIP have the numeric code 292
object GMD extends Currency { given Eql[GMD.type, GMD.type] = Eql.derived } //GMD have the numeric code 270
object GNF extends Currency { given Eql[GNF.type, GNF.type] = Eql.derived } //GNF have the numeric code 324
object GTQ extends Currency { given Eql[GTQ.type, GTQ.type] = Eql.derived } //GTQ have the numeric code 320
object GYD extends Currency { given Eql[GYD.type, GYD.type] = Eql.derived } //GYD have the numeric code 328
object HKD extends Currency { given Eql[HKD.type, HKD.type] = Eql.derived } //HKD have the numeric code 344
object HNL extends Currency { given Eql[HNL.type, HNL.type] = Eql.derived } //HNL have the numeric code 340
object HRK extends Currency { given Eql[HRK.type, HRK.type] = Eql.derived } //HRK have the numeric code 191
object HTG extends Currency { given Eql[HTG.type, HTG.type] = Eql.derived } //HTG have the numeric code 332
object HUF extends Currency { given Eql[HUF.type, HUF.type] = Eql.derived } //HUF have the numeric code 348
object IDR extends Currency { given Eql[IDR.type, IDR.type] = Eql.derived } //IDR have the numeric code 360
object ILS extends Currency { given Eql[ILS.type, ILS.type] = Eql.derived } //ILS have the numeric code 376
object INR extends Currency { given Eql[INR.type, INR.type] = Eql.derived } //INR have the numeric code 356
object IQD extends Currency { given Eql[IQD.type, IQD.type] = Eql.derived } //IQD have the numeric code 368
object IRR extends Currency { given Eql[IRR.type, IRR.type] = Eql.derived } //IRR have the numeric code 364
object ISK extends Currency { given Eql[ISK.type, ISK.type] = Eql.derived } //ISK have the numeric code 352
object JMD extends Currency { given Eql[JMD.type, JMD.type] = Eql.derived } //JMD have the numeric code 388
object JOD extends Currency { given Eql[JOD.type, JOD.type] = Eql.derived } //JOD have the numeric code 400
object JPY extends Currency { given Eql[JPY.type, JPY.type] = Eql.derived } //JPY have the numeric code 392
object KES extends Currency { given Eql[KES.type, KES.type] = Eql.derived } //KES have the numeric code 404
object KGS extends Currency { given Eql[KGS.type, KGS.type] = Eql.derived } //KGS have the numeric code 417
object KHR extends Currency { given Eql[KHR.type, KHR.type] = Eql.derived } //KHR have the numeric code 116
object KMF extends Currency { given Eql[KMF.type, KMF.type] = Eql.derived } //KMF have the numeric code 174
object KPW extends Currency { given Eql[KPW.type, KPW.type] = Eql.derived } //KPW have the numeric code 408
object KRW extends Currency { given Eql[KRW.type, KRW.type] = Eql.derived } //KRW have the numeric code 410
object KWD extends Currency { given Eql[KWD.type, KWD.type] = Eql.derived } //KWD have the numeric code 414
object KYD extends Currency { given Eql[KYD.type, KYD.type] = Eql.derived } //KYD have the numeric code 136
object KZT extends Currency { given Eql[KZT.type, KZT.type] = Eql.derived } //KZT have the numeric code 398
object LAK extends Currency { given Eql[LAK.type, LAK.type] = Eql.derived } //LAK have the numeric code 418
object LBP extends Currency { given Eql[LBP.type, LBP.type] = Eql.derived } //LBP have the numeric code 422
object LKR extends Currency { given Eql[LKR.type, LKR.type] = Eql.derived } //LKR have the numeric code 144
object LRD extends Currency { given Eql[LRD.type, LRD.type] = Eql.derived } //LRD have the numeric code 430
object LSL extends Currency { given Eql[LSL.type, LSL.type] = Eql.derived } //LSL have the numeric code 426
object LYD extends Currency { given Eql[LYD.type, LYD.type] = Eql.derived } //LYD have the numeric code 434
object MAD extends Currency { given Eql[MAD.type, MAD.type] = Eql.derived } //MAD have the numeric code 504
object MDL extends Currency { given Eql[MDL.type, MDL.type] = Eql.derived } //MDL have the numeric code 498
object MGA extends Currency { given Eql[MGA.type, MGA.type] = Eql.derived } //MGA have the numeric code 969
object MKD extends Currency { given Eql[MKD.type, MKD.type] = Eql.derived } //MKD have the numeric code 807
object MMK extends Currency { given Eql[MMK.type, MMK.type] = Eql.derived } //MMK have the numeric code 104
object MNT extends Currency { given Eql[MNT.type, MNT.type] = Eql.derived } //MNT have the numeric code 496
object MOP extends Currency { given Eql[MOP.type, MOP.type] = Eql.derived } //MOP have the numeric code 446
object MRU extends Currency { given Eql[MRU.type, MRU.type] = Eql.derived } //MRU have the numeric code 929
object MUR extends Currency { given Eql[MUR.type, MUR.type] = Eql.derived } //MUR have the numeric code 480
object MVR extends Currency { given Eql[MVR.type, MVR.type] = Eql.derived } //MVR have the numeric code 462
object MWK extends Currency { given Eql[MWK.type, MWK.type] = Eql.derived } //MWK have the numeric code 454
object MXN extends Currency { given Eql[MXN.type, MXN.type] = Eql.derived } //MXN have the numeric code 484
object MXV extends Currency { given Eql[MXV.type, MXV.type] = Eql.derived } //MXV have the numeric code 979
object MYR extends Currency { given Eql[MYR.type, MYR.type] = Eql.derived } //MYR have the numeric code 458
object MZN extends Currency { given Eql[MZN.type, MZN.type] = Eql.derived } //MZN have the numeric code 943
object NAD extends Currency { given Eql[NAD.type, NAD.type] = Eql.derived } //NAD have the numeric code 516
object NGN extends Currency { given Eql[NGN.type, NGN.type] = Eql.derived } //NGN have the numeric code 566
object NIO extends Currency { given Eql[NIO.type, NIO.type] = Eql.derived } //NIO have the numeric code 558
object NOK extends Currency { given Eql[NOK.type, NOK.type] = Eql.derived } //NOK have the numeric code 578
object NPR extends Currency { given Eql[NPR.type, NPR.type] = Eql.derived } //NPR have the numeric code 524
object NZD extends Currency { given Eql[NZD.type, NZD.type] = Eql.derived } //NZD have the numeric code 554
object OMR extends Currency { given Eql[OMR.type, OMR.type] = Eql.derived } //OMR have the numeric code 512
object PAB extends Currency { given Eql[PAB.type, PAB.type] = Eql.derived } //PAB have the numeric code 590
object PEN extends Currency { given Eql[PEN.type, PEN.type] = Eql.derived } //PEN have the numeric code 604
object PGK extends Currency { given Eql[PGK.type, PGK.type] = Eql.derived } //PGK have the numeric code 598
object PHP extends Currency { given Eql[PHP.type, PHP.type] = Eql.derived } //PHP have the numeric code 608
object PKR extends Currency { given Eql[PKR.type, PKR.type] = Eql.derived } //PKR have the numeric code 586
object PLN extends Currency { given Eql[PLN.type, PLN.type] = Eql.derived } //PLN have the numeric code 985
object PYG extends Currency { given Eql[PYG.type, PYG.type] = Eql.derived } //PYG have the numeric code 600
object QAR extends Currency { given Eql[QAR.type, QAR.type] = Eql.derived } //QAR have the numeric code 634
object RON extends Currency { given Eql[RON.type, RON.type] = Eql.derived } //RON have the numeric code 946
object RSD extends Currency { given Eql[RSD.type, RSD.type] = Eql.derived } //RSD have the numeric code 941
object RUB extends Currency { given Eql[RUB.type, RUB.type] = Eql.derived } //RUB have the numeric code 643
object RWF extends Currency { given Eql[RWF.type, RWF.type] = Eql.derived } //RWF have the numeric code 646
object SAR extends Currency { given Eql[SAR.type, SAR.type] = Eql.derived } //SAR have the numeric code 682
object SBD extends Currency { given Eql[SBD.type, SBD.type] = Eql.derived } //SBD have the numeric code 090
object SCR extends Currency { given Eql[SCR.type, SCR.type] = Eql.derived } //SCR have the numeric code 690
object SDG extends Currency { given Eql[SDG.type, SDG.type] = Eql.derived } //SDG have the numeric code 938
object SEK extends Currency { given Eql[SEK.type, SEK.type] = Eql.derived } //SEK have the numeric code 752
object SGD extends Currency { given Eql[SGD.type, SGD.type] = Eql.derived } //SGD have the numeric code 702
object SHP extends Currency { given Eql[SHP.type, SHP.type] = Eql.derived } //SHP have the numeric code 654
object SLL extends Currency { given Eql[SLL.type, SLL.type] = Eql.derived } //SLL have the numeric code 694
object SOS extends Currency { given Eql[SOS.type, SOS.type] = Eql.derived } //SOS have the numeric code 706
object SRD extends Currency { given Eql[SRD.type, SRD.type] = Eql.derived } //SRD have the numeric code 968
object SSP extends Currency { given Eql[SSP.type, SSP.type] = Eql.derived } //SSP have the numeric code 728
object STN extends Currency { given Eql[STN.type, STN.type] = Eql.derived } //STN have the numeric code 930
object SVC extends Currency { given Eql[SVC.type, SVC.type] = Eql.derived } //SVC have the numeric code 222
object SYP extends Currency { given Eql[SYP.type, SYP.type] = Eql.derived } //SYP have the numeric code 760
object SZL extends Currency { given Eql[SZL.type, SZL.type] = Eql.derived } //SZL have the numeric code 748
object THB extends Currency { given Eql[THB.type, THB.type] = Eql.derived } //THB have the numeric code 764
object TJS extends Currency { given Eql[TJS.type, TJS.type] = Eql.derived } //TJS have the numeric code 972
object TMT extends Currency { given Eql[TMT.type, TMT.type] = Eql.derived } //TMT have the numeric code 934
object TND extends Currency { given Eql[TND.type, TND.type] = Eql.derived } //TND have the numeric code 788
object TOP extends Currency { given Eql[TOP.type, TOP.type] = Eql.derived } //TOP have the numeric code 776
object TRY extends Currency { given Eql[TRY.type, TRY.type] = Eql.derived } //TRY have the numeric code 949
object TTD extends Currency { given Eql[TTD.type, TTD.type] = Eql.derived } //TTD have the numeric code 780
object TWD extends Currency { given Eql[TWD.type, TWD.type] = Eql.derived } //TWD have the numeric code 901
object TZS extends Currency { given Eql[TZS.type, TZS.type] = Eql.derived } //TZS have the numeric code 834
object UAH extends Currency { given Eql[UAH.type, UAH.type] = Eql.derived } //UAH have the numeric code 980
object UGX extends Currency { given Eql[UGX.type, UGX.type] = Eql.derived } //UGX have the numeric code 800
object USD extends Currency { given Eql[USD.type, USD.type] = Eql.derived } //USD have the numeric code 840
object USN extends Currency { given Eql[USN.type, USN.type] = Eql.derived } //USN have the numeric code 997
object UYI extends Currency { given Eql[UYI.type, UYI.type] = Eql.derived } //UYI have the numeric code 940
object UYU extends Currency { given Eql[UYU.type, UYU.type] = Eql.derived } //UYU have the numeric code 858
object UYW extends Currency { given Eql[UYW.type, UYW.type] = Eql.derived } //UYW have the numeric code 927
object UZS extends Currency { given Eql[UZS.type, UZS.type] = Eql.derived } //UZS have the numeric code 860
object VES extends Currency { given Eql[VES.type, VES.type] = Eql.derived } //VES have the numeric code 928
object VND extends Currency { given Eql[VND.type, VND.type] = Eql.derived } //VND have the numeric code 704
object VUV extends Currency { given Eql[VUV.type, VUV.type] = Eql.derived } //VUV have the numeric code 548
object WST extends Currency { given Eql[WST.type, WST.type] = Eql.derived } //WST have the numeric code 882
object XAF extends Currency { given Eql[XAF.type, XAF.type] = Eql.derived } //XAF have the numeric code 950
object XAG extends Currency { given Eql[XAG.type, XAG.type] = Eql.derived } //XAG have the numeric code 961
object XAU extends Currency { given Eql[XAU.type, XAU.type] = Eql.derived } //XAU have the numeric code 959
object XBA extends Currency { given Eql[XBA.type, XBA.type] = Eql.derived } //XBA have the numeric code 955
object XBB extends Currency { given Eql[XBB.type, XBB.type] = Eql.derived } //XBB have the numeric code 956
object XBC extends Currency { given Eql[XBC.type, XBC.type] = Eql.derived } //XBC have the numeric code 957
object XBD extends Currency { given Eql[XBD.type, XBD.type] = Eql.derived } //XBD have the numeric code 958
object XCD extends Currency { given Eql[XCD.type, XCD.type] = Eql.derived } //XCD have the numeric code 951
object XDR extends Currency { given Eql[XDR.type, XDR.type] = Eql.derived } //XDR have the numeric code 960
object XOF extends Currency { given Eql[XOF.type, XOF.type] = Eql.derived } //XOF have the numeric code 952
object XPD extends Currency { given Eql[XPD.type, XPD.type] = Eql.derived } //XPD have the numeric code 964
object XPF extends Currency { given Eql[XPF.type, XPF.type] = Eql.derived } //XPF have the numeric code 953
object XPT extends Currency { given Eql[XPT.type, XPT.type] = Eql.derived } //XPT have the numeric code 962
object XSU extends Currency { given Eql[XSU.type, XSU.type] = Eql.derived } //XSU have the numeric code 994
object XTS extends Currency { given Eql[XTS.type, XTS.type] = Eql.derived } //XTS have the numeric code 963
object XUA extends Currency { given Eql[XUA.type, XUA.type] = Eql.derived } //XUA have the numeric code 965
object XXX extends Currency { given Eql[XXX.type, XXX.type] = Eql.derived } //XXX have the numeric code 999
object YER extends Currency { given Eql[YER.type, YER.type] = Eql.derived } //YER have the numeric code 886
object ZAR extends Currency { given Eql[ZAR.type, ZAR.type] = Eql.derived } //ZAR have the numeric code 710
object ZMW extends Currency { given Eql[ZMW.type, ZMW.type] = Eql.derived } //ZMW have the numeric code 967
object ZWL extends Currency { given Eql[ZWL.type, ZWL.type] = Eql.derived } //ZWL have the numeric code 932



// object Currency {
//   //import sala.language.strictEquality
//   class AED extends Currency { given Eql[AED, AED] = Eql.derived } //AED have the numeric code 784
//   class AFN extends Currency { given Eql[AFN, AFN] = Eql.derived } //AFN have the numeric code 971
//   class ALL extends Currency { given Eql[ALL, ALL] = Eql.derived } //ALL have the numeric code 008
//   class AMD extends Currency { given Eql[AMD, AMD] = Eql.derived } //AMD have the numeric code 051
//   class ANG extends Currency { given Eql[ANG, ANG] = Eql.derived } //ANG have the numeric code 532
//   class AOA extends Currency { given Eql[AOA, AOA] = Eql.derived } //AOA have the numeric code 973
//   class ARS extends Currency { given Eql[ARS, ARS] = Eql.derived } //ARS have the numeric code 032
//   class AUD extends Currency { given Eql[AUD, AUD] = Eql.derived } //AUD have the numeric code 036
//   class AWG extends Currency { given Eql[AWG, AWG] = Eql.derived } //AWG have the numeric code 533
//   class AZN extends Currency { given Eql[AZN, AZN] = Eql.derived } //AZN have the numeric code 944
//   class BAM extends Currency { given Eql[BAM, BAM] = Eql.derived } //BAM have the numeric code 977
//   class BBD extends Currency { given Eql[BBD, BBD] = Eql.derived } //BBD have the numeric code 052
//   class BDT extends Currency { given Eql[BDT, BDT] = Eql.derived } //BDT have the numeric code 050
//   class BGN extends Currency { given Eql[BGN, BGN] = Eql.derived } //BGN have the numeric code 975
//   class BHD extends Currency { given Eql[BHD, BHD] = Eql.derived } //BHD have the numeric code 048
//   class BIF extends Currency { given Eql[BIF, BIF] = Eql.derived } //BIF have the numeric code 108
//   class BMD extends Currency { given Eql[BMD, BMD] = Eql.derived } //BMD have the numeric code 060
//   class BND extends Currency { given Eql[BND, BND] = Eql.derived } //BND have the numeric code 096
//   class BOB extends Currency { given Eql[BOB, BOB] = Eql.derived } //BOB have the numeric code 068
//   class BOV extends Currency { given Eql[BOV, BOV] = Eql.derived } //BOV have the numeric code 984
//   class BRL extends Currency { given Eql[BRL, BRL] = Eql.derived } //BRL have the numeric code 986
//   class BSD extends Currency { given Eql[BSD, BSD] = Eql.derived } //BSD have the numeric code 044
//   class BTN extends Currency { given Eql[BTN, BTN] = Eql.derived } //BTN have the numeric code 064
//   class BWP extends Currency { given Eql[BWP, BWP] = Eql.derived } //BWP have the numeric code 072
//   class BYN extends Currency { given Eql[BYN, BYN] = Eql.derived } //BYN have the numeric code 933
//   class BZD extends Currency { given Eql[BZD, BZD] = Eql.derived } //BZD have the numeric code 084
//   class CAD extends Currency { given Eql[CAD, CAD] = Eql.derived } //CAD have the numeric code 124
//   class CDF extends Currency { given Eql[CDF, CDF] = Eql.derived } //CDF have the numeric code 976
//   class CHE extends Currency { given Eql[CHE, CHE] = Eql.derived } //CHE have the numeric code 947
//   class CHF extends Currency { given Eql[CHF, CHF] = Eql.derived } //CHF have the numeric code 756
//   class CHW extends Currency { given Eql[CHW, CHW] = Eql.derived } //CHW have the numeric code 948
//   class CLF extends Currency { given Eql[CLF, CLF] = Eql.derived } //CLF have the numeric code 990
//   class CLP extends Currency { given Eql[CLP, CLP] = Eql.derived } //CLP have the numeric code 152
//   class CNY extends Currency { given Eql[CNY, CNY] = Eql.derived } //CNY have the numeric code 156
//   class COP extends Currency { given Eql[COP, COP] = Eql.derived } //COP have the numeric code 170
//   class COU extends Currency { given Eql[COU, COU] = Eql.derived } //COU have the numeric code 970
//   class CRC extends Currency { given Eql[CRC, CRC] = Eql.derived } //CRC have the numeric code 188
//   class CUC extends Currency { given Eql[CUC, CUC] = Eql.derived } //CUC have the numeric code 931
//   class CUP extends Currency { given Eql[CUP, CUP] = Eql.derived } //CUP have the numeric code 192
//   class CVE extends Currency { given Eql[CVE, CVE] = Eql.derived } //CVE have the numeric code 132
//   class CZK extends Currency { given Eql[CZK, CZK] = Eql.derived } //CZK have the numeric code 203
//   class DJF extends Currency { given Eql[DJF, DJF] = Eql.derived } //DJF have the numeric code 262
//   class DKK extends Currency { given Eql[DKK, DKK] = Eql.derived } //DKK have the numeric code 208
//   class DOP extends Currency { given Eql[DOP, DOP] = Eql.derived } //DOP have the numeric code 214
//   class DZD extends Currency { given Eql[DZD, DZD] = Eql.derived } //DZD have the numeric code 012
//   class EGP extends Currency { given Eql[EGP, EGP] = Eql.derived } //EGP have the numeric code 818
//   class ERN extends Currency { given Eql[ERN, ERN] = Eql.derived } //ERN have the numeric code 232
//   class ETB extends Currency { given Eql[ETB, ETB] = Eql.derived } //ETB have the numeric code 230
//   class EUR extends Currency { given Eql[EUR, EUR] = Eql.derived } //EUR have the numeric code 978
//   class FJD extends Currency { given Eql[FJD, FJD] = Eql.derived } //FJD have the numeric code 242
//   class FKP extends Currency { given Eql[FKP, FKP] = Eql.derived } //FKP have the numeric code 238
//   class GBP extends Currency { given Eql[GBP, GBP] = Eql.derived } //GBP have the numeric code 826
//   class GEL extends Currency { given Eql[GEL, GEL] = Eql.derived } //GEL have the numeric code 981
//   class GHS extends Currency { given Eql[GHS, GHS] = Eql.derived } //GHS have the numeric code 936
//   class GIP extends Currency { given Eql[GIP, GIP] = Eql.derived } //GIP have the numeric code 292
//   class GMD extends Currency { given Eql[GMD, GMD] = Eql.derived } //GMD have the numeric code 270
//   class GNF extends Currency { given Eql[GNF, GNF] = Eql.derived } //GNF have the numeric code 324
//   class GTQ extends Currency { given Eql[GTQ, GTQ] = Eql.derived } //GTQ have the numeric code 320
//   class GYD extends Currency { given Eql[GYD, GYD] = Eql.derived } //GYD have the numeric code 328
//   class HKD extends Currency { given Eql[HKD, HKD] = Eql.derived } //HKD have the numeric code 344
//   class HNL extends Currency { given Eql[HNL, HNL] = Eql.derived } //HNL have the numeric code 340
//   class HRK extends Currency { given Eql[HRK, HRK] = Eql.derived } //HRK have the numeric code 191
//   class HTG extends Currency { given Eql[HTG, HTG] = Eql.derived } //HTG have the numeric code 332
//   class HUF extends Currency { given Eql[HUF, HUF] = Eql.derived } //HUF have the numeric code 348
//   class IDR extends Currency { given Eql[IDR, IDR] = Eql.derived } //IDR have the numeric code 360
//   class ILS extends Currency { given Eql[ILS, ILS] = Eql.derived } //ILS have the numeric code 376
//   class INR extends Currency { given Eql[INR, INR] = Eql.derived } //INR have the numeric code 356
//   class IQD extends Currency { given Eql[IQD, IQD] = Eql.derived } //IQD have the numeric code 368
//   class IRR extends Currency { given Eql[IRR, IRR] = Eql.derived } //IRR have the numeric code 364
//   class ISK extends Currency { given Eql[ISK, ISK] = Eql.derived } //ISK have the numeric code 352
//   class JMD extends Currency { given Eql[JMD, JMD] = Eql.derived } //JMD have the numeric code 388
//   class JOD extends Currency { given Eql[JOD, JOD] = Eql.derived } //JOD have the numeric code 400
//   class JPY extends Currency { given Eql[JPY, JPY] = Eql.derived } //JPY have the numeric code 392
//   class KES extends Currency { given Eql[KES, KES] = Eql.derived } //KES have the numeric code 404
//   class KGS extends Currency { given Eql[KGS, KGS] = Eql.derived } //KGS have the numeric code 417
//   class KHR extends Currency { given Eql[KHR, KHR] = Eql.derived } //KHR have the numeric code 116
//   class KMF extends Currency { given Eql[KMF, KMF] = Eql.derived } //KMF have the numeric code 174
//   class KPW extends Currency { given Eql[KPW, KPW] = Eql.derived } //KPW have the numeric code 408
//   class KRW extends Currency { given Eql[KRW, KRW] = Eql.derived } //KRW have the numeric code 410
//   class KWD extends Currency { given Eql[KWD, KWD] = Eql.derived } //KWD have the numeric code 414
//   class KYD extends Currency { given Eql[KYD, KYD] = Eql.derived } //KYD have the numeric code 136
//   class KZT extends Currency { given Eql[KZT, KZT] = Eql.derived } //KZT have the numeric code 398
//   class LAK extends Currency { given Eql[LAK, LAK] = Eql.derived } //LAK have the numeric code 418
//   class LBP extends Currency { given Eql[LBP, LBP] = Eql.derived } //LBP have the numeric code 422
//   class LKR extends Currency { given Eql[LKR, LKR] = Eql.derived } //LKR have the numeric code 144
//   class LRD extends Currency { given Eql[LRD, LRD] = Eql.derived } //LRD have the numeric code 430
//   class LSL extends Currency { given Eql[LSL, LSL] = Eql.derived } //LSL have the numeric code 426
//   class LYD extends Currency { given Eql[LYD, LYD] = Eql.derived } //LYD have the numeric code 434
//   class MAD extends Currency { given Eql[MAD, MAD] = Eql.derived } //MAD have the numeric code 504
//   class MDL extends Currency { given Eql[MDL, MDL] = Eql.derived } //MDL have the numeric code 498
//   class MGA extends Currency { given Eql[MGA, MGA] = Eql.derived } //MGA have the numeric code 969
//   class MKD extends Currency { given Eql[MKD, MKD] = Eql.derived } //MKD have the numeric code 807
//   class MMK extends Currency { given Eql[MMK, MMK] = Eql.derived } //MMK have the numeric code 104
//   class MNT extends Currency { given Eql[MNT, MNT] = Eql.derived } //MNT have the numeric code 496
//   class MOP extends Currency { given Eql[MOP, MOP] = Eql.derived } //MOP have the numeric code 446
//   class MRU extends Currency { given Eql[MRU, MRU] = Eql.derived } //MRU have the numeric code 929
//   class MUR extends Currency { given Eql[MUR, MUR] = Eql.derived } //MUR have the numeric code 480
//   class MVR extends Currency { given Eql[MVR, MVR] = Eql.derived } //MVR have the numeric code 462
//   class MWK extends Currency { given Eql[MWK, MWK] = Eql.derived } //MWK have the numeric code 454
//   class MXN extends Currency { given Eql[MXN, MXN] = Eql.derived } //MXN have the numeric code 484
//   class MXV extends Currency { given Eql[MXV, MXV] = Eql.derived } //MXV have the numeric code 979
//   class MYR extends Currency { given Eql[MYR, MYR] = Eql.derived } //MYR have the numeric code 458
//   class MZN extends Currency { given Eql[MZN, MZN] = Eql.derived } //MZN have the numeric code 943
//   class NAD extends Currency { given Eql[NAD, NAD] = Eql.derived } //NAD have the numeric code 516
//   class NGN extends Currency { given Eql[NGN, NGN] = Eql.derived } //NGN have the numeric code 566
//   class NIO extends Currency { given Eql[NIO, NIO] = Eql.derived } //NIO have the numeric code 558
//   class NOK extends Currency { given Eql[NOK, NOK] = Eql.derived } //NOK have the numeric code 578
//   class NPR extends Currency { given Eql[NPR, NPR] = Eql.derived } //NPR have the numeric code 524
//   class NZD extends Currency { given Eql[NZD, NZD] = Eql.derived } //NZD have the numeric code 554
//   class OMR extends Currency { given Eql[OMR, OMR] = Eql.derived } //OMR have the numeric code 512
//   class PAB extends Currency { given Eql[PAB, PAB] = Eql.derived } //PAB have the numeric code 590
//   class PEN extends Currency { given Eql[PEN, PEN] = Eql.derived } //PEN have the numeric code 604
//   class PGK extends Currency { given Eql[PGK, PGK] = Eql.derived } //PGK have the numeric code 598
//   class PHP extends Currency { given Eql[PHP, PHP] = Eql.derived } //PHP have the numeric code 608
//   class PKR extends Currency { given Eql[PKR, PKR] = Eql.derived } //PKR have the numeric code 586
//   class PLN extends Currency { given Eql[PLN, PLN] = Eql.derived } //PLN have the numeric code 985
//   class PYG extends Currency { given Eql[PYG, PYG] = Eql.derived } //PYG have the numeric code 600
//   class QAR extends Currency { given Eql[QAR, QAR] = Eql.derived } //QAR have the numeric code 634
//   class RON extends Currency { given Eql[RON, RON] = Eql.derived } //RON have the numeric code 946
//   class RSD extends Currency { given Eql[RSD, RSD] = Eql.derived } //RSD have the numeric code 941
//   class RUB extends Currency { given Eql[RUB, RUB] = Eql.derived } //RUB have the numeric code 643
//   class RWF extends Currency { given Eql[RWF, RWF] = Eql.derived } //RWF have the numeric code 646
//   class SAR extends Currency { given Eql[SAR, SAR] = Eql.derived } //SAR have the numeric code 682
//   class SBD extends Currency { given Eql[SBD, SBD] = Eql.derived } //SBD have the numeric code 090
//   class SCR extends Currency { given Eql[SCR, SCR] = Eql.derived } //SCR have the numeric code 690
//   class SDG extends Currency { given Eql[SDG, SDG] = Eql.derived } //SDG have the numeric code 938
//   class SEK extends Currency { given Eql[SEK, SEK] = Eql.derived } //SEK have the numeric code 752
//   class SGD extends Currency { given Eql[SGD, SGD] = Eql.derived } //SGD have the numeric code 702
//   class SHP extends Currency { given Eql[SHP, SHP] = Eql.derived } //SHP have the numeric code 654
//   class SLL extends Currency { given Eql[SLL, SLL] = Eql.derived } //SLL have the numeric code 694
//   class SOS extends Currency { given Eql[SOS, SOS] = Eql.derived } //SOS have the numeric code 706
//   class SRD extends Currency { given Eql[SRD, SRD] = Eql.derived } //SRD have the numeric code 968
//   class SSP extends Currency { given Eql[SSP, SSP] = Eql.derived } //SSP have the numeric code 728
//   class STN extends Currency { given Eql[STN, STN] = Eql.derived } //STN have the numeric code 930
//   class SVC extends Currency { given Eql[SVC, SVC] = Eql.derived } //SVC have the numeric code 222
//   class SYP extends Currency { given Eql[SYP, SYP] = Eql.derived } //SYP have the numeric code 760
//   class SZL extends Currency { given Eql[SZL, SZL] = Eql.derived } //SZL have the numeric code 748
//   class THB extends Currency { given Eql[THB, THB] = Eql.derived } //THB have the numeric code 764
//   class TJS extends Currency { given Eql[TJS, TJS] = Eql.derived } //TJS have the numeric code 972
//   class TMT extends Currency { given Eql[TMT, TMT] = Eql.derived } //TMT have the numeric code 934
//   class TND extends Currency { given Eql[TND, TND] = Eql.derived } //TND have the numeric code 788
//   class TOP extends Currency { given Eql[TOP, TOP] = Eql.derived } //TOP have the numeric code 776
//   class TRY extends Currency { given Eql[TRY, TRY] = Eql.derived } //TRY have the numeric code 949
//   class TTD extends Currency { given Eql[TTD, TTD] = Eql.derived } //TTD have the numeric code 780
//   class TWD extends Currency { given Eql[TWD, TWD] = Eql.derived } //TWD have the numeric code 901
//   class TZS extends Currency { given Eql[TZS, TZS] = Eql.derived } //TZS have the numeric code 834
//   class UAH extends Currency { given Eql[UAH, UAH] = Eql.derived } //UAH have the numeric code 980
//   class UGX extends Currency { given Eql[UGX, UGX] = Eql.derived } //UGX have the numeric code 800
//   class USD extends Currency { given Eql[USD, USD] = Eql.derived } //USD have the numeric code 840
//   class USN extends Currency { given Eql[USN, USN] = Eql.derived } //USN have the numeric code 997
//   class UYI extends Currency { given Eql[UYI, UYI] = Eql.derived } //UYI have the numeric code 940
//   class UYU extends Currency { given Eql[UYU, UYU] = Eql.derived } //UYU have the numeric code 858
//   class UYW extends Currency { given Eql[UYW, UYW] = Eql.derived } //UYW have the numeric code 927
//   class UZS extends Currency { given Eql[UZS, UZS] = Eql.derived } //UZS have the numeric code 860
//   class VES extends Currency { given Eql[VES, VES] = Eql.derived } //VES have the numeric code 928
//   class VND extends Currency { given Eql[VND, VND] = Eql.derived } //VND have the numeric code 704
//   class VUV extends Currency { given Eql[VUV, VUV] = Eql.derived } //VUV have the numeric code 548
//   class WST extends Currency { given Eql[WST, WST] = Eql.derived } //WST have the numeric code 882
//   class XAF extends Currency { given Eql[XAF, XAF] = Eql.derived } //XAF have the numeric code 950
//   class XAG extends Currency { given Eql[XAG, XAG] = Eql.derived } //XAG have the numeric code 961
//   class XAU extends Currency { given Eql[XAU, XAU] = Eql.derived } //XAU have the numeric code 959
//   class XBA extends Currency { given Eql[XBA, XBA] = Eql.derived } //XBA have the numeric code 955
//   class XBB extends Currency { given Eql[XBB, XBB] = Eql.derived } //XBB have the numeric code 956
//   class XBC extends Currency { given Eql[XBC, XBC] = Eql.derived } //XBC have the numeric code 957
//   class XBD extends Currency { given Eql[XBD, XBD] = Eql.derived } //XBD have the numeric code 958
//   class XCD extends Currency { given Eql[XCD, XCD] = Eql.derived } //XCD have the numeric code 951
//   class XDR extends Currency { given Eql[XDR, XDR] = Eql.derived } //XDR have the numeric code 960
//   class XOF extends Currency { given Eql[XOF, XOF] = Eql.derived } //XOF have the numeric code 952
//   class XPD extends Currency { given Eql[XPD, XPD] = Eql.derived } //XPD have the numeric code 964
//   class XPF extends Currency { given Eql[XPF, XPF] = Eql.derived } //XPF have the numeric code 953
//   class XPT extends Currency { given Eql[XPT, XPT] = Eql.derived } //XPT have the numeric code 962
//   class XSU extends Currency { given Eql[XSU, XSU] = Eql.derived } //XSU have the numeric code 994
//   class XTS extends Currency { given Eql[XTS, XTS] = Eql.derived } //XTS have the numeric code 963
//   class XUA extends Currency { given Eql[XUA, XUA] = Eql.derived } //XUA have the numeric code 965
//   class XXX extends Currency { given Eql[XXX, XXX] = Eql.derived } //XXX have the numeric code 999
//   class YER extends Currency { given Eql[YER, YER] = Eql.derived } //YER have the numeric code 886
//   class ZAR extends Currency { given Eql[ZAR, ZAR] = Eql.derived } //ZAR have the numeric code 710
//   class ZMW extends Currency { given Eql[ZMW, ZMW] = Eql.derived } //ZMW have the numeric code 967
//   class ZWL extends Currency { given Eql[ZWL, ZWL] = Eql.derived } //ZWL have the numeric code 932
// }
